tourmate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tours.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('destinasi/<int:pk>/', views.DetailDestinasi.as_view(), name='detail'),
    path("city/", views.IndexView.as_view(), name="search_results"),
    path('plan', views.IndexPlanView.as_view(), name="plan_list"),
    path('plan/<int:pk>/', views.RencanaDetail.as_view(), name='detail_rencana'),
    path('destination', views.IndexDestinasiController.as_view(), name="destination"),
    path('destination/<int:page>', views.IndexDestinasiController.as_view(), name="destination_list"),
    path('plan/create', views.RencanaWisataController.as_view(), name="create_plan"),
    path("destination/", views.IndexDestinasiController.as_view(), name="search_destination_results"),
    path('register', views.RegisterController.as_view(), name='register'),
    path('login', auth_view.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True),
         name='login'),
    # path('logins', views.LoginView, name="logins"),
    path('logout', auth_view.LogoutView.as_view(template_name='tours/index.html'), name='logout'),
    path('addPost', views.CreatePostController.as_view(), name='addPost'),
    path('explore', views.IndexPostView.as_view(), name='indexPost'),
    path('posts/<str:username>/', views.PostsController.as_view(), name='posts'),
    path('posts/<str:username>/<int:id>/', views.PostsController.as_view(), name='post'),
    path('posts/<str:username>/<int:id>/update', views.PostUpdateController.as_view(), name='postUpdate'),
    path('posts/<str:username>/<int:id>/delete', views.PostDeleteController.as_view(), name='postDelete'),
    path('profile', views.UserProfile.as_view(), name='users-profile'),
]

tours/models.py
from datetime import datetime, date
from django.db import models
from django.contrib.auth.models import User, AbstractUser


# Create your models here.
class User(AbstractUser):
    profile_pic = models.ImageField(upload_to='images/user_profile', default='images/user_profile/default12998.png')
    tanggal_lahir = models.DateField(null=True)


class Kota(models.Model):
    city = models.CharField(max_length=50, primary_key=True)
    province = models.CharField(max_length=50, null=True)
    related_city = models.CharField(max_length=50, blank=True)
    image = models.ImageField(upload_to='images/city', null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.city


class Destinasi(models.Model):
    CATEGORY_CHOICE = [
        ('Wisata Alam', 'Wisata Alam'),
        ('Taman Bermain', 'Taman Bermain'),
        ('Tempat Bersejarah', 'Tempat Bersejarah'),
        ('Kebun Binatang', 'Kebun Binatang'),
        ('Wisata Seni', 'Wisata Seni'),
        ('Pusat Belanja', 'Pusat Belanja'),
        ('Bangunan Unik', 'Bangunan Unik'),
    ]
    name = models.CharField(max_length=200)
    categories = models.CharField(max_length=200, choices=CATEGORY_CHOICE, null=True)
    image_path = models.ImageField(upload_to='images')
    address = models.CharField(max_length=200)
    maps = models.CharField(max_length=1500, null=True)
    panorama = models.CharField(max_length=1500, null=True)
    kecamatan = models.CharField(max_length=200, null=True)
    city = models.ForeignKey(Kota, on_delete=models.CASCADE)
    description = models.CharField(max_length=22200, null=True)
    opening_hours = models.TimeField(null=True)
    closing_hours = models.TimeField(null=True)
    price_min = models.IntegerField()
    price_max = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    rating = models.FloatField(null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return str([self.name, self.city, self.price_max])


class Akomodasi(models.Model):
    accomodation_name = models.CharField(max_length=200, null=True)
    city = models.ForeignKey(Kota, on_delete=models.CASCADE)
    price_per_night = models.IntegerField()
    address = models.CharField(max_length=200)
    image_path = models.ImageField(upload_to='images')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str([self.accomodation_name, self.price_per_night, self.city])


class Transportasi(models.Model):
    MODA_CHOICES = [
        ('BUS', 'Bus'),
        ('TRAIN', 'Kereta Api'),
        ('PLANE', 'Pesawat'),
    ]
    name = models.CharField(max_length=200, null=True)
    moda = models.CharField(max_length=200, choices=MODA_CHOICES)
    city_from = models.ForeignKey(Kota, on_delete=models.CASCADE)
    city_to = models.ForeignKey(Kota, related_name='city_to', on_delete=models.CASCADE)
    depart_time = models.TimeField()
    arrive_time = models.TimeField()
    duration = models.DurationField(null=True, blank=True)
    price_per_person = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def save(self, *args, **kwargs):
        self.duration = datetime.combine(date.min, self.arrive_time) - datetime.combine(date.min, self.depart_time)
        super(Transportasi, self).save(*args, **kwargs)

    def __str__(self):
        return str([self.name, self.city_from, self.city_to, self.price_per_person])


class RencanaWisata(models.Model):
    title = models.CharField(max_length=200, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    budget = models.FloatField()
    city_start = models.ForeignKey(Kota, on_delete=models.CASCADE)
    city_dest = models.ForeignKey(Kota, related_name='user_city_dest', on_delete=models.CASCADE)
    days = models.IntegerField()
    transportasi_pergi = models.ForeignKey(Transportasi, on_delete=models.CASCADE, null=True)
    transportasi_pulang = models.ForeignKey(Transportasi, related_name='tp_pulang', on_delete=models.CASCADE,
                                            null=True)
    akomodasi = models.ForeignKey(Akomodasi, on_delete=models.CASCADE, null=True)
    destination = models.ManyToManyField(Destinasi, related_name='user_rencana_destinasi',
                                         through='RencanaWisataDestinasi')
    real_cost = models.FloatField(null=True)


class RencanaWisataDestinasi(models.Model):
    destinasi = models.ForeignKey(Destinasi, on_delete=models.CASCADE)
    rencana_wisata = models.ForeignKey(RencanaWisata, on_delete=models.CASCADE)
    day = models.IntegerField()
    start_time = models.TimeField()
    end_time = models.TimeField(null=True)


class Postingan(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, default='Judul')
    image_path = models.ImageField(upload_to='images/post')
    caption = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    destinasi = models.ForeignKey(Destinasi, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

tours/views/CreatePost.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views import View
from tours.forms import CreatePostForm
from tours.models import User


class CreatePostController(View):
    form_class = CreatePostForm
    initial = {'key': 'value'}
    template_name = 'tours/explore/AddPostUI.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'test': len(kwargs)})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(pk=request.user.id)
            obj.save()
            messages.success(request, f'Pstingan Berhasil Ditambahkan')
            return redirect('/posts/' + request.user.username + '/')
        return render(request, self.template_name, {'form': form})

tours/views/DetailDestinasi.py
from django.views import generic

from tours.models import Destinasi


class DetailDestinasi(generic.DetailView):
    model = Destinasi
    template_name = 'tours/destination/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailDestinasi, self).get_context_data(*args, **kwargs)
        return context

tours/views/IndexController.py
from django.contrib.gis.geoip2 import GeoIP2
from django.db.models import Q, Case, When, Value, BooleanField
from django.views import generic

from tours.models import Kota, Postingan, Destinasi


class IndexView(generic.ListView):
    template_name = 'tours/index.html'
    context_object_name = 'tour_list'

    def get_ip(self):
        user_ip = self.request.META.get('HTTP_X_FORWARDED_FOR')  # real ip user
        if user_ip:
            ip = user_ip.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')  # ip komputer client
        g = GeoIP2()  # manggil library
        if ip == '127.0.0.1':
            city = g.city('103.165.157.4')
        else:
            city = g.city(ip) #cari kota based on ip
        return city

    def get_city_from_ip(self, ip):
        g = GeoIP2()  # manggil library
        if ip == '' :
            return False
        if ip == '127.0.0.1':
            city = g.city('103.165.157.4')
        else:
            city = g.city(ip)  # cari kota based on ip
        return city

    def get_city_list(self):
        return Kota.objects.values('city', 'province')

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        user_city = self.get_ip()
        if self.request.GET.get("city") is not None:
            user_city['city'] = self.request.GET.get("city")
        context['city'] = Kota.objects.all()
        context['location'] = user_city
        context['city_list'] = self.get_city_list()
        context['post'] = Postingan.objects.all().order_by('-created_at')[:4]
        return context

    def divide_chunks(self, obj):
        n = 4
        # looping till length l
        for i in range(0, len(obj), n):
            yield obj[i:i + n]

    def get_queryset(self):
        user_city = self.get_ip()
        if self.request.GET.get("city") is not None:
            user_city['city'] = self.request.GET.get("city")
        g = Destinasi.objects.filter(
            Q(city__city=user_city['city']) | Q(city__related_city=user_city['city'])).annotate(
            relevancy=Case(When(city=user_city['city'], then=Value(True)), output_field=BooleanField())).order_by(
            'relevancy')[:12]
        if not g:
            g = Destinasi.objects.all()[:12]
        return list(self.divide_chunks(g))

tours/views/IndexDestinasi.py
from django.db.models import *
from django.views import generic

from tours.models import Kota, Destinasi
from tours.views.IndexController import IndexView


class IndexDestinasiController(generic.ListView):
    template_name = 'tours/destination/destination_list.html'
    context_object_name = 'destination_list'
    paginate_by = 20
    def get_context_data(self, *args, **kwargs):
        context = super(IndexDestinasiController, self).get_context_data(*args, **kwargs)
        user_city = IndexView.get_ip(self)
        if self.request.GET.get("location") is not None:
            user_city['city'] = self.request.GET.get("location")
        if self.request.GET.get("cari_destinasi"):
            filtered = self.search_by_name()
            context['searched'] = filtered
        context['location'] = user_city
        context['city'] = Kota.objects.all()

        return context

    def search_by_name(self):
        keyword = self.request.GET.get("cari_destinasi")
        city = self.request.GET.get("location")
        if city in ['Semua', '']:
            q = Destinasi.objects.filter(name__icontains=keyword)
        elif keyword:
            q = Destinasi.objects.filter(name__icontains=keyword, city__city=city)
        if q:
            return q
        else:
            return 'Tidak ditemukan'

    def search(self, keyword):
        if keyword:
            q = Destinasi.objects.filter(name__icontains=keyword)
            if q:
                return q
            else:
                return 'Tidak ditemukan'
        else:
            return False



    def get_queryset(self):
        user_city = IndexView.get_ip(self)
        if self.request.GET.get("location") is not None or Empty:
            user_city['city'] = self.request.GET.get("location")
        g = Destinasi.objects.filter(
            Q(city__city=user_city['city']) | Q(city__related_city=user_city['city'])).annotate(
            relevancy=Case(When(city=user_city['city'], then=Value(True)), output_field=BooleanField())).order_by(
            'relevancy')
        if not g:
            g = Destinasi.objects.all()
        return g

tours/views/IndexPost.py
from django.views import generic

from tours.models import User, Postingan


class IndexPostView(generic.ListView):
    template_name = "tours/explore/IndexPostUI.html"

    def get_context_data(self, *args, **kwargs):
        context = super(IndexPostView, self).get_context_data(*args, **kwargs)
        context['user_list'] = User.objects.all()[:6]
        return context

    def get_queryset(self):
        return Postingan.objects.all().order_by('-created_at')

tours/views/IndexRencanaWisata.py
from django.views import generic

from tours.models import Kota, RencanaWisata
from tours.views.IndexController import IndexView


class IndexPlanView(generic.ListView):
    template_name = 'tours/tour_plan/plan_list.html'
    context_object_name = 'plan_list'

    def get_context_data(self, *args, **kwargs):
        user_city = IndexView.get_ip(self)
        if self.request.GET.get("city") is not None:
            user_city['city'] = self.request.GET.get("city")
        context = super(IndexPlanView, self).get_context_data(*args, **kwargs)
        context['location'] = user_city
        context['city'] = Kota.objects.all()
        if self.request.user.is_authenticated :
            context['user_plan'] = RencanaWisata.objects.filter(user=self.request.user)
        return context

    def get_queryset(self):
        return RencanaWisata.objects.all()

tours/views/PostDelete.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect
from django.views import View

from tours.models import Postingan


class PostDeleteController(View):
    initial = {'key': 'value'}
    template_name = 'PostsUI.html'

    def post(self, request, *args, **kwargs):
        p = Postingan.objects.get(id=kwargs['id'])
        if str(kwargs['username']) != str(p.user):
            raise Http404
        r = Postingan.objects.filter(id=kwargs['id'])
        r.delete()
        messages.success(request, f'Post was successfully deleted')
        return redirect('/posts/' + kwargs['username'] + '/')

tours/views/PostsController.py
from django.shortcuts import redirect, render
from django.views import View

from tours.models import Postingan


class PostsController(View):
    initial = {'key': 'value'}
    template_name = 'tours/explore/PostsUI.html'

    def get(self, request, *args, **kwargs):
        if kwargs['username'] != request.user.username:
            return redirect('/login')
        else:
            data = Postingan.objects.filter(user=request.user.id)
            return render(request, self.template_name, {'data': data})

tours/views/RegisterController.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views import View

from tours.forms import CreateUserForm


class RegisterController(View):
    form_class = CreateUserForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hi {username}, your account was successfully created')
            return redirect('index')
        return render(request, self.template_name, {'form': form})

tours/templates/tours/explore/AddPostUI.html
{% include "tours/layout/header.html" %}
<nav class="navbar navbar-expand-lg sticky-top" style="height: 78px;">
    {% include "tours/layout/navbar.html" %}
</nav>
<main class="d-flex justify-content-center" style="align-items: center; height: 550px;">
    <div class="  d-flex justify-content-center align-center"
         style="flex-wrap: wrap;  background-color: #f6f6f6; width: 60%; border-radius: 20px">
        <div class="head-post" style="padding-left: 40px !important;">
            <div class="row">
                <div class="col-2" style="text-align: left">
                    <button class="no-decoration" onclick="history.back()"><span class="material-symbols-outlined" style="margin-right: 12px">
arrow_back
</span></button> </div>
                <div class="col-8">{% if test is 0 %}
                    <h4>Create Post</h4>
                {% else %}
                    <h4>Update Post</h4>
                {% endif %}</div>
            </div>

        </div>
        <div class="input-post" style="width: 100%;">
            <form class="add-post" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {#                <div>#}
                {#                    #}
                {#                    {{ form.image_path }}                    </div>#}
                <div class="mb-3">
                    <label for="id_image_path" class="form-label"></label>
                    <input class="form-control" type="file" id="id_image_path" name="image_path">
                    {% for err in form.image_path.errors %}
                        <small class="text-danger">{{ err }}</small>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label for="id_title" class="form-label">Judul</label>
                    <input type="text" class="form-control" name="title" id="id_title"
                           placeholder="Masukkan judul" required
                           value="{% if form.title.value %}{{ form.title.value }} {% endif %}">
                    {% for err in form.title.errors %}
                        <small class="text-danger">{{ err }}</small>
                    {% endfor %}
                </div>
                <div class="mb-3">

                    <textarea class="form-control" name="caption" id="id_caption" rows="5"
                              placeholder="Tulis caption">{% if form.caption.value %}{{ form.caption.value }}{% endif %}</textarea>
                    {% for err in form.caption.errors %}
                        <small class="text-danger">{{ err }}</small>
                    {% endfor %}
                </div>

             {{ form.destinasi }}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>

</main>


</body>
</html>

tours/templates/tours/explore/IndexPostUI.html
{% load static %}
{% include "tours/layout/header.html" %}
<main>
    <nav class="navbar navbar-expand-lg" style="height: 65px">


        {% include "tours/layout/navbar.html" %}


    </nav>
    <div class="row">
        <div class="col-sm-3 d-flex justify-content-center sticky-top" style="height: 100%; flex-wrap: wrap">
        {% include "tours/explore/layout/sidemenu.html" %}
        </div>
        <div class="col-sm-6 pt-5">
            {% for posts in object_list %}


                <div class="card py-3 mb-5"
                     style="width: 100%; border-radius: 10px;box-shadow: -4px -4px 16px rgba(0, 0, 0, 0.06), 4px 4px 16px rgba(0, 0, 0, 0.06);">
                    <div class="post-content" style=" ">
                        <a> <img src="https://dealinbucket.s3.amazonaws.com/static/{{ posts.user.profile_pic }}" height="24"
                                 width="24"> &nbsp;{{ posts.user.username }} </a>

                        <h4 class="card-title text-truncate">{{ posts.title }}</h4>
                        <p class="pb-3">{{ posts.created_at }}</p>


                        <img src="https://dealinbucket.s3.amazonaws.com/static/{{ posts.image_path }}"
                             class="card-img-top"
                             style="height: 350px; border-radius: 10px; object-fit: cover"
                             alt="">
                        <div class="post-par pt-4">
                            <p class="card-title">{{ posts.caption }}</p>
                        </div>

                    </div>
                </div>

            {% endfor %}
        </div>
        <div class="col-sm-3 sticky-top" style="    z-index: 1 !important;padding-left: 3%; height: 100%">
            <div class="menu-explore py-5 " style="text-align: left; width: 56%; position: sticky">
                {% include 'tours/explore/layout/addpost.html' %}

                <h5 class="pb-3">SUGGESTIONS</h5>
                {% for user in user_list %}
                    <div class="menu-explore-item">
                        <a> <img src="https://dealinbucket.s3.amazonaws.com/static/{{ user.profile_pic }}" height="24"
                                 width="24"> &nbsp;{{ user.username }} </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

</main>
</body>
</html>

tours/templates/tours/explore/PostsUI.html
{% load static %}
{% include "tours/layout/header.html" %}
<main>
    <nav class="navbar navbar-expand-lg" style="height: 65px">


        {% include "tours/layout/navbar.html" %}


    </nav>
    <div class="row">
        <div class="col-sm-3 d-flex justify-content-center sticky-top" style="height: 100%; flex-wrap: wrap">
            {% include "tours/explore/layout/sidemenu.html" %}
        </div>
        <div class="col-sm-6 pt-5">
            {% if data %}
                <div class="head-post mb-2" style="font-weight: 600; text-align: left; padding: 0 !important;">
                    <h4>
                        <button class="no-decoration" onclick="history.back()"><span class="material-symbols-outlined"
                                                                                     style="margin-right: 12px">arrow_back
</span></button>
                        Postingan saya
                    </h4>
                </div>
                {% for posts in data %}
                    <div class="card py-3 mb-5"
                         style="width: 100%; border-radius: 10px;box-shadow: -4px -4px 16px rgba(0, 0, 0, 0.06), 4px 4px 16px rgba(0, 0, 0, 0.06);">
                        <div class="post-content" style=" ">

                            <h4 class="card-title text-truncate">{{ posts.title }}</h4>
                            <p class="pb-3">{{ posts.created_at }}</p>
                            <img src="https://dealinbucket.s3.amazonaws.com/static/{{ posts.image_path }}"
                                 class="card-img-top"
                                 style="height: 350px; border-radius: 10px; object-fit: cover"
                                 alt="">
                            <div class="post-par pt-4">
                                <p class="card-title">{{ posts.caption }}</p>
                            </div>
                            <div class="d-flex">
                                <a href="{{ posts.id }}/update">
                                    <button type="button" class="btn btn-primary">Perbarui
                                    </button>
                                </a>

                                <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                        data-bs-target="#deleteModal" style="margin-left: 10px"><span
                                        class="material-symbols-outlined">delete</span>Hapus
                                </button>

                                <div class="modal fade" id="deleteModal" tabindex="-1"
                                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="exampleModalLabel">Konfirmasi</h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Anda yakin ingin menghapus postingan ini ?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                                    Batal
                                                </button>
                                                <form action="{{ posts.id }}/delete" method="post"
                                                      style="margin-left: 10px">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger">Hapus</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% else %}
                <h6>Anda belum mengunggah post</h6>
            {% endif %}
        </div>
        <div class="col-sm-3 sticky-top" style="    z-index: 1 !important;padding-left: 3%; height: 100%">
            <div class="menu-explore py-5 " style="text-align: left; width: 56%; position: sticky">
                {% include 'tours/explore/layout/addpost.html' %}

            </div>
        </div>
    </div>

</main>
</body>

</html>